name:                Wordcrab
version:             0.1.0.0
github:              "undergroundquizscene/wordcrab"
license:             BSD3
author:              "Emily Bourke"
maintainer:          "undergroundquizscene@protonmail.com"
copyright:           "Emily Bourke"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/undergroundquizscene/wordcrab#readme>

dependencies:
- base
- io-streams
- aeson
- network
- bytestring
- random
- transformers
- vector
- random-shuffle
- brick
- vty
- lens
- text
- containers
- servant
- servant-server
- servant-client
- warp
- http-client
- wai-extra
- http-types

library:
  source-dirs: src

executables:
  wordcrab-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Wordcrab

tests:
  Wordcrab-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Wordcrab
